// 語源（語根）で共通した英単語データ
// 各グループは共通の語根（root）を持ち、その語根の意味と派生単語を含む
const VOCAB_DATA = [
  {
    root: "port",
    rootMeaning: "運ぶ (carry)",
    origin: "ラテン語 portare",
    words: [
      { word: "import", meaning: "輸入する", note: "in(中へ)+port(運ぶ)" },
      { word: "export", meaning: "輸出する", note: "ex(外へ)+port(運ぶ)" },
      { word: "transport", meaning: "輸送する", note: "trans(越えて)+port(運ぶ)" },
      { word: "portable", meaning: "持ち運びできる", note: "port(運ぶ)+able(できる)" },
      { word: "porter", meaning: "荷物運搬人、ポーター", note: "port(運ぶ)+er(人)" },
    ],
  },
  {
    root: "spect",
    rootMeaning: "見る (look)",
    origin: "ラテン語 spectare",
    words: [
      { word: "inspect", meaning: "検査する", note: "in(中を)+spect(見る)" },
      { word: "respect", meaning: "尊敬する", note: "re(再び)+spect(見る)" },
      { word: "spectator", meaning: "観客", note: "spect(見る)+ator(人)" },
      { word: "prospect", meaning: "見込み、展望", note: "pro(前を)+spect(見る)" },
      { word: "suspect", meaning: "疑う", note: "sus(下から)+spect(見る)" },
    ],
  },
  {
    root: "dict",
    rootMeaning: "言う (say)",
    origin: "ラテン語 dicere",
    words: [
      { word: "predict", meaning: "予言する、予測する", note: "pre(前もって)+dict(言う)" },
      { word: "dictate", meaning: "書き取らせる、命令する", note: "dict(言う)+ate" },
      { word: "contradict", meaning: "矛盾する、否定する", note: "contra(反対に)+dict(言う)" },
      { word: "verdict", meaning: "評決、判決", note: "ver(真実)+dict(言う)" },
      { word: "dictionary", meaning: "辞書", note: "dict(言う)+ionary" },
    ],
  },
  {
    root: "struct",
    rootMeaning: "建てる (build)",
    origin: "ラテン語 struere",
    words: [
      { word: "construct", meaning: "建設する", note: "con(共に)+struct(建てる)" },
      { word: "structure", meaning: "構造、建造物", note: "struct(建てる)+ure" },
      { word: "instruct", meaning: "教える、指示する", note: "in(上に)+struct(建てる)" },
      { word: "destruct", meaning: "破壊する", note: "de(下に)+struct(建てる)" },
      { word: "obstruct", meaning: "妨害する", note: "ob(向かって)+struct(建てる)" },
    ],
  },
  {
    root: "vis / vid",
    rootMeaning: "見る (see)",
    origin: "ラテン語 videre",
    words: [
      { word: "vision", meaning: "視力、視覚、展望", note: "vis(見る)+ion" },
      { word: "visible", meaning: "目に見える", note: "vis(見る)+ible(できる)" },
      { word: "evident", meaning: "明白な", note: "e(外に)+vid(見る)+ent" },
      { word: "provide", meaning: "供給する、備える", note: "pro(前もって)+vid(見る)" },
      { word: "supervise", meaning: "監督する", note: "super(上から)+vis(見る)" },
    ],
  },
  {
    root: "form",
    rootMeaning: "形 (shape)",
    origin: "ラテン語 forma",
    words: [
      { word: "reform", meaning: "改革する", note: "re(再び)+form(形作る)" },
      { word: "transform", meaning: "変形させる", note: "trans(越えて)+form(形)" },
      { word: "uniform", meaning: "制服、均一の", note: "uni(一つ)+form(形)" },
      { word: "conform", meaning: "従う、適合する", note: "con(共に)+form(形)" },
      { word: "formal", meaning: "正式な、形式的な", note: "form(形)+al" },
    ],
  },
  {
    root: "tract",
    rootMeaning: "引く (draw / pull)",
    origin: "ラテン語 trahere",
    words: [
      { word: "attract", meaning: "引きつける", note: "at(～へ)+tract(引く)" },
      { word: "contract", meaning: "契約、収縮する", note: "con(共に)+tract(引く)" },
      { word: "extract", meaning: "抽出する、抜き取る", note: "ex(外へ)+tract(引く)" },
      { word: "distract", meaning: "気を散らす", note: "dis(離れて)+tract(引く)" },
      { word: "subtract", meaning: "引き算する", note: "sub(下に)+tract(引く)" },
    ],
  },
  {
    root: "ject",
    rootMeaning: "投げる (throw)",
    origin: "ラテン語 jacere",
    words: [
      { word: "reject", meaning: "拒絶する", note: "re(後ろへ)+ject(投げる)" },
      { word: "project", meaning: "計画、投影する", note: "pro(前へ)+ject(投げる)" },
      { word: "inject", meaning: "注射する、注入する", note: "in(中へ)+ject(投げる)" },
      { word: "eject", meaning: "排出する、追い出す", note: "e(外へ)+ject(投げる)" },
      { word: "object", meaning: "物体、反対する", note: "ob(向かって)+ject(投げる)" },
    ],
  },
  {
    root: "scrib / script",
    rootMeaning: "書く (write)",
    origin: "ラテン語 scribere",
    words: [
      { word: "describe", meaning: "描写する、説明する", note: "de(下に)+scrib(書く)" },
      { word: "prescribe", meaning: "処方する、規定する", note: "pre(前もって)+scrib(書く)" },
      { word: "manuscript", meaning: "原稿、写本", note: "manu(手)+script(書く)" },
      { word: "subscribe", meaning: "購読する、署名する", note: "sub(下に)+scrib(書く)" },
      { word: "inscribe", meaning: "刻む、銘記する", note: "in(中に)+scrib(書く)" },
    ],
  },
  {
    root: "mit / miss",
    rootMeaning: "送る (send)",
    origin: "ラテン語 mittere",
    words: [
      { word: "submit", meaning: "提出する、服従する", note: "sub(下に)+mit(送る)" },
      { word: "transmit", meaning: "送信する、伝達する", note: "trans(越えて)+mit(送る)" },
      { word: "mission", meaning: "任務、使命", note: "miss(送る)+ion" },
      { word: "dismiss", meaning: "解雇する、退ける", note: "dis(離れて)+miss(送る)" },
      { word: "permit", meaning: "許可する", note: "per(通して)+mit(送る)" },
    ],
  },
  {
    root: "ped",
    rootMeaning: "足 (foot)",
    origin: "ラテン語 pes / pedis",
    words: [
      { word: "pedal", meaning: "ペダル、足踏み板", note: "ped(足)+al" },
      { word: "pedestrian", meaning: "歩行者", note: "ped(足)+estrian" },
      { word: "expedite", meaning: "迅速に処理する", note: "ex(外へ)+ped(足)" },
      { word: "centipede", meaning: "ムカデ", note: "centi(百)+ped(足)" },
      { word: "pedestal", meaning: "台座", note: "ped(足)+estal" },
    ],
  },
  {
    root: "graph",
    rootMeaning: "書く・描く (write / draw)",
    origin: "ギリシャ語 graphein",
    words: [
      { word: "photograph", meaning: "写真", note: "photo(光)+graph(描く)" },
      { word: "biography", meaning: "伝記", note: "bio(生命)+graph(書く)" },
      { word: "paragraph", meaning: "段落", note: "para(横に)+graph(書く)" },
      { word: "autograph", meaning: "署名、サイン", note: "auto(自分)+graph(書く)" },
      { word: "geography", meaning: "地理学", note: "geo(地球)+graph(書く)" },
    ],
  },
  {
    root: "tele",
    rootMeaning: "遠い (far / distant)",
    origin: "ギリシャ語 tele",
    words: [
      { word: "telephone", meaning: "電話", note: "tele(遠く)+phone(音)" },
      { word: "television", meaning: "テレビ", note: "tele(遠く)+vision(視覚)" },
      { word: "telescope", meaning: "望遠鏡", note: "tele(遠く)+scope(見る)" },
      { word: "telegram", meaning: "電報", note: "tele(遠く)+gram(書いたもの)" },
      { word: "telepathy", meaning: "テレパシー、精神感応", note: "tele(遠く)+pathy(感情)" },
    ],
  },
  {
    root: "man / manu",
    rootMeaning: "手 (hand)",
    origin: "ラテン語 manus",
    words: [
      { word: "manual", meaning: "手動の、説明書", note: "manu(手)+al" },
      { word: "manufacture", meaning: "製造する", note: "manu(手)+facture(作る)" },
      { word: "manage", meaning: "管理する、何とかやる", note: "man(手)+age" },
      { word: "manipulate", meaning: "操作する、操る", note: "mani(手)+pulate" },
      { word: "manuscript", meaning: "原稿、写本", note: "manu(手)+script(書く)" },
    ],
  },
  {
    root: "bio",
    rootMeaning: "生命 (life)",
    origin: "ギリシャ語 bios",
    words: [
      { word: "biology", meaning: "生物学", note: "bio(生命)+logy(学問)" },
      { word: "biography", meaning: "伝記", note: "bio(生命)+graphy(書く)" },
      { word: "antibiotic", meaning: "抗生物質", note: "anti(対抗)+bio(生命)" },
      { word: "symbiosis", meaning: "共生", note: "sym(共に)+bio(生命)" },
      { word: "biosphere", meaning: "生物圏", note: "bio(生命)+sphere(圏)" },
    ],
  },
];
